"""Build a double-clickable Mac .app that opens the Track List web app.

The bundle is a thin launcher around the repo's own venv — nothing is frozen
or copied, so the app always runs whatever code is on disk. On every launch it
replaces any previous server (no stale-code windows), waits for the port to
answer, then opens a Chrome app-mode window (own window, no tabs — the export
pipeline is tuned to Chrome's codecs); if Chrome is missing it falls back to
the default browser. The icon is drawn as a vinyl record with a pure-stdlib
PNG writer and converted with macOS's sips/iconutil — best-effort, the app
works fine without it."""

from __future__ import annotations

import math
import plistlib
import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path

APP_NAME = "releases"
BUNDLE_ID = "net.music-ops.releases"


# ---- icon: a vinyl record, no imaging deps ----

def write_vinyl_png(path: Path, size: int) -> Path:
    """Draw the icon and write a valid RGBA PNG using only stdlib."""
    s = size
    cx = cy = (s - 1) / 2.0
    disc_r = s * 0.47
    label_r = s * 0.175
    hole_r = s * 0.030
    rows = bytearray()
    for y in range(s):
        rows.append(0)  # filter: None
        for x in range(s):
            r = math.hypot(x - cx, y - cy)
            if r > disc_r:
                rows += b"\x00\x00\x00\x00"
                continue
            a = 255 if r < disc_r - 1 else max(0, min(255, int((disc_r - r) * 255)))
            if r < hole_r:
                px = (12, 12, 14)
            elif r < label_r:
                # brass label with a soft top-light
                f = 1.0 - 0.25 * ((y - cy) / label_r + 1) / 2
                px = (int(212 * f), int(170 * f), int(94 * f))
            else:
                # grooves: fine alternating rings on near-black
                g = 18 + int(8 * (0.5 + 0.5 * math.sin(r * 1.9)))
                px = (g, g, g + 3)
            rows += bytes((px[0], px[1], px[2], a))
    def chunk(tag: bytes, body: bytes) -> bytes:
        return (struct.pack(">I", len(body)) + tag + body
                + struct.pack(">I", zlib.crc32(tag + body) & 0xFFFFFFFF))
    ihdr = struct.pack(">IIBBBBB", s, s, 8, 6, 0, 0, 0)  # 8-bit RGBA
    png = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
           + chunk(b"IDAT", zlib.compress(bytes(rows), 9)) + chunk(b"IEND", b""))
    path.write_bytes(png)
    return path


def _make_icns(res_dir: Path) -> str | None:
    """PNG -> .icns via sips + iconutil (macOS only). Returns the icon filename
    for Info.plist, or None if anything is unavailable — the app still works."""
    try:
        with tempfile.TemporaryDirectory() as td:
            iconset = Path(td) / "releases.iconset"
            iconset.mkdir()
            base = Path(td) / "base.png"
            write_vinyl_png(base, 1024)
            for pt in (16, 32, 128, 256, 512):
                for scale, suffix in ((1, ""), (2, "@2x")):
                    px = pt * scale
                    out = iconset / f"icon_{pt}x{pt}{suffix}.png"
                    subprocess.run(
                        ["sips", "-z", str(px), str(px), str(base), "--out", str(out)],
                        check=True, capture_output=True)
            icns = res_dir / "releases.icns"
            subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(icns)],
                           check=True, capture_output=True)
            return icns.name
    except Exception:
        return None


# ---- the bundle ----

_LAUNCHER = """#!/bin/bash
# releases.app launcher - generated by `releases macapp`
BIN="{bin_path}"
PORT={port}
URL="http://127.0.0.1:$PORT"
LOGDIR="$HOME/Library/Logs"
PIDFILE="$HOME/.releases/webapp.pid"
mkdir -p "$HOME/.releases" "$LOGDIR"
# always restart the server so the window never shows stale code
if [ -f "$PIDFILE" ]; then kill "$(cat "$PIDFILE")" 2>/dev/null; sleep 0.4; fi
lsof -tiTCP:$PORT -sTCP:LISTEN 2>/dev/null | xargs kill 2>/dev/null
sleep 0.3
nohup "$BIN" web --port "$PORT"{artist_arg} >>"$LOGDIR/releases-web.log" 2>&1 &
echo $! > "$PIDFILE"
for i in $(seq 1 60); do
  curl -s -o /dev/null "$URL" && break
  sleep 0.25
done
# Chrome app mode = its own window, and the codecs the exporter is tuned for
if ! open -na "Google Chrome" --args --app="$URL" 2>/dev/null; then
  open "$URL"
fi
"""


def build_app(dest: Path, *, port: int = 8765, artist: str = "",
              bin_path: Path | None = None) -> Path:
    """Write <dest>/releases.app and return its path."""
    if bin_path is None:
        bin_path = Path(sys.executable).parent / "releases"
    bundle = dest / f"{APP_NAME}.app"
    macos = bundle / "Contents" / "MacOS"
    res = bundle / "Contents" / "Resources"
    macos.mkdir(parents=True, exist_ok=True)
    res.mkdir(parents=True, exist_ok=True)

    artist_arg = f' --artist "{artist}"' if artist else ""
    launcher = macos / "launcher"
    launcher.write_text(_LAUNCHER.format(bin_path=bin_path, port=port, artist_arg=artist_arg))
    launcher.chmod(0o755)

    icon_name = _make_icns(res)
    plist: dict = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": "1.0",
        "CFBundleShortVersionString": "1.0",
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": "launcher",
        "LSMinimumSystemVersion": "12.0",
        # the wrapper starts the server + opens the window, then exits:
        # no lingering generic icon bouncing in the dock
        "LSUIElement": True,
    }
    if icon_name:
        plist["CFBundleIconFile"] = icon_name
    (bundle / "Contents" / "Info.plist").write_bytes(plistlib.dumps(plist))
    return bundle
